#!/usr/bin/env python

import sys
import os
from myplotstyle import AcademicPlot  # 确保 myplotstyle 在您的 Python 路径下

# 检查是否有命令行参数传入
if len(sys.argv) > 1:
    file_path = sys.argv[1]  # 使用命令行指定的文件
else:
    file_path = './opt_IPOPT.txt'  # 如果没有指定文件，则在当前目录查找opt_IPOPT.txt

objectives = []  # 初始化列表来存储目标值
start_reading = False  # 标记变量，用于确定何时开始读取数据

with open(file_path, 'r') as file:
    for line in file:
        line = line.strip()  # 去除行首尾的空白字符（包括换行符和空格）

        if line.startswith('iter'):
            start_reading = True
            continue  # 跳过包含'iter'的行
        if not line:
            start_reading = False
            continue
        if start_reading:
            parts = line.split()
            if len(parts) > 1:
                objective = float(parts[1])
                objectives.append(objective)  # 将目标值添加到列表中
            else:
                print(f"数据格式错误或行不完整: {line}")
                continue  # 跳过这行或做一些其他的错误处理

# 使用 AcademicPlot 创建图表
plot = AcademicPlot(figsize=(8,6))
plot.plot(list(range(1,len(objectives)+1)), objectives)  # 绘制目标值
plot.set_title("Loss Over Iterations")
plot.set_xlabel("Iteration")
plot.set_ylabel("Loss")
plot.enable_scientific_notation(axis='both')

if not os.path.exists("./assets"):
    os.makedirs("./assets")

# 显示并保存图表
plot.show()
if len(sys.argv) > 2:
    plot.save(sys.argv[2])
else:
    plot.save('./assets/opt_IPOPT.png')
