#!/usr/bin/env python

import pandas as pd
import yaml
import sys
from myplotstyle import AcademicPlot
import os

def show_yaml_example():
    print("YAML配置文件示例:")
    print("""
transform:
  U0: 5.4
  nu: 1.5e-5

files:
  - path: "path/to/your/rawfile1.raw"
    label: "case1"
    skiprows: 1
    type: "line" # 可选，默认为 'line'
    marker: "o" # 可选
    markerevery: 100 # 可选
    
  - path: "path/to/your/rawfile2.raw"
    label: "case2"
    skiprows: 1
    type: "scatter" # 可选，默认为 'line'
    marker: "x" # 可选
    markerevery: 100 # 可选

exp_files: # (可选)
  - path: "path/to/your/experiment_file.raw"
    label: "Experiment"
    skiprows: 1
    type: "scatter" # 可选，默认为 'line'
    marker: "+" # 可选

plot:
  title: "Plot Title"
  xlabel: "X Axis Label"
  ylabel: "Y Axis Label"
  xlim: [xmin, xmax] # (可选)
  ylim: [ymin, ymax] # (可选)
  figsize: [12, 6]

""")


def read_config(config_file):
    with open(config_file, 'r') as file:
        config = yaml.safe_load(file)
    return config

def read_data(file_path, skiprows):
    # 读取RAW文件
    data = pd.read_csv(file_path, delim_whitespace=True, skiprows=skiprows,header=None)
    data['x'] = data.iloc[:, 0]  # 根据规则计算横坐标
    data['y'] = data.iloc[:, 1]  # 根据规则计算纵坐标
    return data

def read_and_transform_data(file_path, transform_config,skiprows):
    # 读取RAW文件
    data = pd.read_csv(file_path, delim_whitespace=True, skiprows=skiprows,header=None)

    # 应用转换规则
    U0 = transform_config['U0']
    nu = transform_config['nu']
    data['x'] = U0 * data.iloc[:, 0] / nu  
    
    # 如果y>0，取y=2*y/U0^2,否则取y=-2*y/U0^2
    data['y'] = data.iloc[:, 3].apply(lambda y: 2 * y / (U0 * U0) if y > 0 else -2 * y / (U0 * U0))
    
    return data

def plot_data(academic_plot, data, label, marker=None, plot_type='line',markevery=None,show_markers=False):
    x = data['x'].to_numpy()
    y = data['y'].to_numpy()
    
    plot_args = {
        'label': label,
    }
    
    if show_markers:
        plot_args.update({
            'marker': marker,
            'markevery': markevery,
        })
    
    # 绘图
    if plot_type == 'line':
        academic_plot.plot(x, y, **plot_args)
    elif plot_type == 'scatter':
        academic_plot.scatter(x, y, label=label, marker=marker)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python script.py <config.yml>")
        show_yaml_example()
        sys.exit(1)

    config_file = sys.argv[1]
    config = read_config(config_file)

    my_plot = AcademicPlot(figsize=config['plot'].get('figsize', (10, 6)))
    
    for file_config in config['files']:
        skiprows = file_config.get('skiprows', 0)
        data = read_and_transform_data(file_config['path'], config['transform'], skiprows)
        
        config_args = {
            'marker': file_config.get('marker', None),
            'markevery': file_config.get("markevery",None),
            'show_markers': file_config.get('show_markers', False),
            "plot_type": file_config.get('type', 'line'),
            "label": file_config.get('label')
        }
        
        plot_data(my_plot, data,**config_args)
    
    if 'exp_files' in config:
        for file_config in config['exp_files']:
            skiprows = file_config.get('skiprows', 0)
            data = read_data(file_config['path'], skiprows)
            
            config_args = {
                'marker': file_config.get('marker', None),
                'markevery': file_config.get("markevery",None),
                'show_markers': file_config.get('show_markers', True),
                "plot_type": file_config.get('type', 'scatter'),
                "label": file_config.get('label')
            }
            
            plot_data(my_plot, data, **config_args)

    my_plot.set_title(title=config['plot'].get('title', 'Data Plot'))
    my_plot.set_xlabel(xlabel=config['plot'].get('xlabel', ''))
    my_plot.set_ylabel(ylabel=config['plot'].get('ylabel', ''))
    
    xlim = config['plot'].get('xlim')
    if xlim:
        my_plot.ax.set_xlim(xlim[0], xlim[1])

    ylim = config['plot'].get('ylim')
    if ylim:
        my_plot.ax.set_ylim(ylim[0], ylim[1])

    my_plot.show()
    
    if not os.path.exists("./assets"):
        os.makedirs("./assets")

    if 'savefig' in config:
        my_plot.save(config['savefig'])
    else:
        my_plot.save("./assets/cf.png")